### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [t-rex-tileserver/t-rex#20]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

**Comment by pka** [comment]
nickel, the integrated web framework uses rustc-serialize. Will migrate as soon as possible.

**Comment by lnicola** [comment]
@pka Besides being a dependency of `nickel`,`rustc-serialize` seems to only be used in a derive on `TileSetInfo` [here](https://github.com/t-rex-tileserver/t-rex/blob/master/t-rex-webserver/src/server.rs#L42). But unless I'm missing something, that struct isn't used for anything.

Do you think that's part of some incomplete functionality, or can we just drop it? I can include this in #93, since that's already removing a couple of unused dependencies.

**Comment by pka** [comment]
I will work on the migration from nickel to actix-web next week. Will fix this then.

**Comment by lnicola** [comment]
@pka `TileSetInfo` is still there :smile:.
