### ISSUE TITLE
.pbf too large

### ISSUE THREAD

**Issue by xycarto** [t-rex-tileserver/t-rex#213]
I'm running:

t_rex 0.11.0 (GDAL version 2.4.2)
on Ubuntu 18

and creating my own tile grid on a 36MB contour .shp with the following configuration (geometries have been simplified before):

```
[service.mvt]
viewer = true

[[datasource]]
name = "foo"
path = "wellyDEM_contour_50m_simp.shp"

[grid.user]
width = 256
height = 256
extent = { minx = -1000000, miny = 3087000, maxx = 3327000, maxy = 10000000 }
srid = 2193
units = "m"
resolutions = [8960.0,4480.0,2240.0,1120.0,560.0,280.0,140.0,70.0,28.0,14.0,7.0,2.8,1.4,0.7,0.28,0.14,0.07]
origin = "TopLeft"

[[tileset]]
name = "bar"

[[tileset.layer]]
name = "bar"
table_name = "wellyDEM_contour_50m_simp"
geometry_type = "LINESTRING"

[cache.file]
base = "/wellyDEM_contour_50m_simp"

[webserver]
bind = "0.0.0.0"
port = 8080
```

The trouble I am facing is this:

The .pbf files that come out the out the other end are exceptionally large. ~1.5MB each at zoom 8 and they get increasingly larger as the zoom scales increase.  I have tested the same file and grid creation using:

```
ogr2ogr -progress -f MVT wellyDEM_50mContour_nztm_simpwellyDEM_contour_50m_simp.shp -dsco MINZOOM=8 -dsco MAXZOOM=8 -dsco COMPRESS=NO -dsco TILING_SCHEME=EPSG:2193,-1000000,10000000,2293760
```
In the OGR process, the .pbf file size at zoom 8 is ~40KB.

1. Am I setting the config incorrectly?  
2. Or perhaps this is an expected result?
3. Is this potentially a bug when building a custom tile grid?

I really like this tool and would like to continue to use it, but I cannot work with .pbf files of this size in my applications.

**Comment by pka** [comment]
I don't see an obvious mistake in the configuration. It might be a bug when using custom grids with GDAL layers. Would it be possible to make the shapefile available for testing?

**Comment by xycarto** [comment]
Sure can:

https://drive.google.com/file/d/1QpY8YYst6Q669UWZA7k13E94pbKi53cH/view?usp=sharing

In the mean time, I'll test this using PostGIS, geojson, and .gpkg and see if it make a difference

**Comment by xycarto** [comment]
Performance is as expected when using a Postgresql connection.  Nice small tiles placed in the expected locations for NZTM (epsg:2193).  Here is the config I used:

```
[service.mvt]
viewer = true

[[datasource]]
dbconn = "postgresql://postgres:postgres@localhost/nz_data"
name = "dbconn"
default = true

[grid.user]
width = 256
height = 256
extent = { minx = -1000000, miny = 3087000, maxx = 3327000, maxy = 10000000 }
srid = 2193
units = "m"
resolutions = [8960.0,4480.0,2240.0,1120.0,560.0,280.0,140.0,70.0,28.0,14.0,7.0,2.8,1.4,0.7,0.28,0.14,0.07]
origin = "TopLeft"

[[tileset]]
name = "wellycontour_simple"
extent = [174.62123, -41.62564, 176.34760, -40.62968]
[[tileset.layer]]
name = "wellycontour_simple"
table_name = "wellycontour_simple"
geometry_field = "geom"
geometry_type = "MULTILINESTRING"
srid = 2193
buffer_size = 0
#make_valid = true
#simplify = true
#query_limit = 1000

#[[tileset.layer.query]]
#sql = """SELECT geom,gid,id,elev::FLOAT8 FROM 50mcontour WHERE geom && !bbox!"""

#resolutions = [8960.0,4480.0,2240.0,1120.0,560.0,280.0,140.0,70.0,28.0,14.0,7.0,2.8,1.4,0.7,0.28,0.14,0.07]

[cache.file]
base = "../wellyDEM_contour_50m_psql"

[webserver]
bind = "0.0.0.0"
port = 8080
```

With this I ran:
```
t_rex generate --progress true --maxzoom=8 --minzoom=8 --extent=160.6,-55.95,-171.2,-25.88  --config /config.toml
```

I also tested gson and gpkg.

gpkg - same issue as before.  pbf tiles come out at ~2MB at zoom 8 with increasing size per zoom scale, although performance was very fast.

json - the file was too complex to handle

**Comment by arbakker** [comment]
I have had similar results when testing t-rex on a GPGK datasource. 

Back then I was also mystified by this behaviour, after inspecting the content of the individual vector tileserver I discovered that t-rex does not clip the geometries to the tilebounds when configured with a GDAL datasource. Not sure if this is intented behaviour by t-rex, but the the t-rex documentation (https://t-rex.tileserver.ch/doc/reference/) states on item `buffer_size` (somewhat cryptic):

> Tile buffer size in pixels.
> When undefined, line and polygon geometries are not clipped.
> Supported for PostGIS layer only.

Considering that buffer_size is only supported for PostGIS layers, and when no buffer_size is defined geometries are not clipped one can conclude that clipping is only supported for PostGIS layers. 

So why are your vector tiles getting bigger with each zoomlevel?

In order to explain this, I quickly go over what is exactly in a vector tile. Usually a vector tile has a size of 512x512 pixels. The geographic coordinates of the source geometries (PostGIS, GDAL) are converted to the tile coordinate space of 512x512 pixels  (see the [Mapbox vector tile spec](https://docs.mapbox.com/vector-tiles/specification/#encoding-geometry) for a better explanation). 

With each zoomlevel deeper the number of tiles quadruple, and so do the number of pixels per tile. Consider a feature that is fully contained in a tile on zoomlevel n and zoomlevel n+1. On zoomlevel n+1 the number of bytes required to store this geometry in the vector tile will be around 4 times compared to zoomlevel n (ignoring compression for simplicty's sake).

In the case of t-rex with a GDAL datasource features are not clipped before they are put in the vector tiles. So each tile intersecting with a geometry will contain the entire geometry. When features start getting bigger than the tilesize, the filesize of start to grow with each zoomlevel. See the following illustration:

![Schermafbeelding 2020-10-26 212013](https://user-images.githubusercontent.com/3216462/97224196-16059380-17d1-11eb-8687-930810802d78.png)

The three tiles (represented by the black border) on z1, z2 and z3 all intersect with the green polygon. t-rex combined with a GDAL datasource will encode the full unclipped polygon in each tile. With each deeper zoomlevel the tile coordinate space grows with a factor 4, causing the filesize of the vector tiles to grow. 

This problem gets even worse since all tiles intersecting with the green polygon will also contain the full polygon. 

- Zoomlevel 1 has 1 tile intersecting with the polygon > 1 polygon
- Zoomlevel 2 has 4 tiles intersecting with the polygon > 4 polygon 
- Zoomlevel 3 has 8 tiles intersecting with the polygon > 8 polygon (eyeballing it)

This adds another multiplying factor to the size of your tile cache per zoomlevel. 

Hope this explains the issue. Cheers!

**Comment by xycarto** [comment]
Solved for me using Postgres
