### ISSUE TITLE
Plans?

### ISSUE THREAD

**Issue by musicformellons** [t-rex-tileserver/t-rex#74]
As I noticed the rate of commits is slowing down I was wondering what plans are for future of t-rex?

**Comment by pka** [comment]
The priorities are still the same as listed on the [Github board](https://github.com/t-rex-tileserver/t-rex/projects/1). But since I'm working on an other side project for some time now and t-rex fullfills the needs of our customer projects, not much is going on here. This can quickly change if a customer needs some functionality or a pull requests comes in. I'm not getting much feedback from users. Occasionally I meet people on conferences professionally working with t-rex, so I assume it's working at least for them.

**Comment by musicformellons** [comment]
Ok! I use and really like it. Mainly concerned about maintenance currently.
